sprint-1 task AIN-04 Login and Register UI
NatalNineITSolutions/AINinja pull request #2
Opened 2024-01-08 12:18 UTC by Jeba-Jeba

**no changes are made to any links on the page.**

Out put on large screen:
![UI lg screen](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/fbfb1c6d-65e9-4fba-bed9-8e68b7495b43)

Out put on small/med screen:
![UI small view](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/5a3f9015-d8e7-4b5b-b68b-0ee5262395d8)

2024-01-08 12:26 UTC, NatalNineITSolutions commented
Give the screenshots of login response form network tab

2024-01-08 12:27 UTC, NatalNineITSolutions commented
Use full width we dont need the whitespace 

![image](https://github.com/NatalNineITSolutions/AINinja/assets/149093208/eaf6d79d-7151-4575-84bc-2d055e1b493f)

2024-01-08 12:29 UTC, NatalNineITSolutions requested changes
Please give screenshots of login response when you get from network tab 
and we don't need whitespace in login UI i mentioned in the screenshot refer that

2024-01-08 12:31 UTC, NatalNineITSolutions commented on routes/web.php
> +if ($installed === false) {
make this default

2024-01-09 11:45 UTC, Jeba-Jeba commented
removed the space on the both side that you told to remove yesterday,
![loginnofill](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/92636959-0475-4782-8f29-6f57171ac3b5)

login page after filling details
![loginfilled](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/d8259ca8-6de9-4918-a4ae-058718905e96)

login response for non  registered user login
![wronglogin](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/ec7029d2-675b-4d60-a9f3-4db7a5d076e6)

Registration UI
![regisnofill](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/94917702-5133-4f59-9a9e-453f503a7455)

registration UI after filling details
![regfilled](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/3d6fd675-3094-4e2b-af72-8fc1c12ba998)

signUp providing a auth error
![signuperr](https://github.com/NatalNineITSolutions/AINinja/assets/153291598/a5bec2b2-dc42-43ca-9bea-c9a8e5000fff)

2024-01-09 15:51 UTC, closed without merging